// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbyJrsvYm2FygmRUzlHLikpQ_d09PK8S7EQ9pnssh5ZB4UA93Ek6AKe4A5wK7BgBWInK/exec";
