name: Calendar Event Fetcher

on:
  schedule:
    - cron: "0 1 * * *" # 3am UTC+2
  workflow_dispatch:

jobs:
  fetch-events:
    name: Fetch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Get Creds
        run: |
          echo "${GOOGLE_CREDENTIALS}" > credentials.json
          cat credentials.json
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Fetch Google Calendar events
        run: |          
          python fetch_events.py

      - name: Modify url_switcher.js with URL's of the day
        run: |
          TIME_URL_LIST_CONTENT=$(<events.txt)
          awk -v new_content="$TIME_URL_LIST_CONTENT" '/const timeUrlList = `/{print; print new_content; p=1; next} !p; p==1 && /`;/ {print "`;\n"; p=0}' url_switcher.js > /tmp/url_switcher.js.tmp
          mv /tmp/url_switcher.js.tmp url_switcher.js

      - name: Commit event URL's to JS file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add url_switcher.js
          git commit -m "Update url_switcher.js with today's URLs"
          git pull --rebase origin ${{ github.ref }}
          git push origin HEAD:${{ github.ref }}
