name: Calendar Event Fetcher

on:
  schedule:
    - cron: "0 1 * * *" # 3am UTC+2

jobs:
  fetch-events:
    name: Fetch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Fetch Google Calendar events
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json
          python fetch_events.py

      - name: Modify url_switcher.js with URL's of the day
      - run: |
          TIME_URL_LIST_CONTENT=$(<events.txt)
          awk -v new_content="$TIME_URL_LIST_CONTENT" '/const timeUrlList = `/{print; print new_content; p=1; next} !p; p==1 && /`;/ {print "`;\n"; p=0}' url_switcher.js > /tmp/url_switcher.js.tmp
          mv /tmp/url_switcher.js.tmp url_switcher.js

      - name: Commit event and JS files
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "github-actions@github.com"
          git add url_switcher.js
          git commit -m "Update url_switcher.js"
          git push
